import{_ as a,c as e,a1 as o,o as t}from"./chunks/framework.BRP8cXOc.js";const n="/agentforce-workshop/data-cloud-11-soql-1.CkwAL-XE.webp",h=JSON.parse('{"title":"Exercise 12 (Optional): Access Data Cloud with SOQL","description":"","frontmatter":{},"headers":[],"relativePath":"agentforce-workshop/data-cloud/11-data-cloud-soql.md","filePath":"agentforce-workshop/data-cloud/11-data-cloud-soql.md"}'),l={name:"agentforce-workshop/data-cloud/11-data-cloud-soql.md"};function i(p,s,c,r,d,_){return t(),e("div",null,s[0]||(s[0]=[o('<h1 id="exercise-12-optional-access-data-cloud-with-soql" tabindex="-1">Exercise 12 (Optional): Access Data Cloud with SOQL <a class="header-anchor" href="#exercise-12-optional-access-data-cloud-with-soql" aria-label="Permalink to &quot;Exercise 12 (Optional): Access Data Cloud with SOQL&quot;">​</a></h1><p>In this exercise, you’ll access Data Cloud data using SOQL.</p><ol><li><p>Using the App Launcher, open the <strong>Code Builder</strong> application.</p></li><li><p>Click <strong>Launch</strong> (this will take a few minutes to open).</p></li><li><p>Right-click the <strong>scripts&gt;soql</strong> folder and create a <strong>New File</strong> called <strong>individual.soql</strong>.</p><p><img src="'+n+`" alt="" data-zoomable="true"></p></li><li><p>In the individual.soql editor window, create a query to return Individual Id, First Name, Last Name, Birth Date, and Data Source Id, where Last Name is equal to <strong>Rodriguez</strong>.</p><div class="language-sql"><button title="Copy Code" class="copy"></button><span class="lang">sql</span><pre class="shiki Codey High Noon vp-code" tabindex="0"><code><span class="line"><span style="color:#0A121C;">SELECT ssot__Id__c,</span></span>
<span class="line"><span style="color:#0A121C;">       ssot__FirstName__c,</span></span>
<span class="line"><span style="color:#0A121C;">       ssot__LastName__c,</span></span>
<span class="line"><span style="color:#0A121C;">       ssot__BirthDate__c,</span></span>
<span class="line"><span style="color:#0A121C;">       ssot__DataSourceId__c</span></span>
<span class="line"><span style="color:#0A121C;">FROM ssot__Individual__dlm</span></span>
<span class="line"><span style="color:#0A121C;">WHERE ssot__LastName__c </span><span style="color:#2C3E50;font-style:italic;font-weight:bold;">=</span><span style="color:#0F4880;"> &#39;Rodriguez&#39;</span></span>
<span class="line"><span style="color:#0A121C;">LIMIT </span><span style="color:#22313F;">100</span></span></code></pre></div></li><li><p><strong>Highlight the query</strong>, then open the command palette (Cmd+Shift+P Mac or Ctrl+Shift+P Windows) and select <strong>SFDX: Execute SOQL Query with Currently Selected Text</strong>.</p><p>You should now see a single record: the consolidated profile created by the identity resolution process.</p></li><li><p>Modify the query as follows:</p><div class="language-sql"><button title="Copy Code" class="copy"></button><span class="lang">sql</span><pre class="shiki Codey High Noon vp-code" tabindex="0"><code><span class="line"><span style="color:#0A121C;">SELECT ssot__Id__c,</span></span>
<span class="line"><span style="color:#0A121C;">      ssot__FirstName__c,</span></span>
<span class="line"><span style="color:#0A121C;">      ssot__LastName__c,</span></span>
<span class="line"><span style="color:#0A121C;">      ssot__BirthDate__c</span></span>
<span class="line"><span style="color:#0A121C;">FROM UnifiedssotIndividualCcid__dlm</span></span>
<span class="line"><span style="color:#0A121C;">WHERE ssot__LastName__c </span><span style="color:#2C3E50;font-style:italic;font-weight:bold;">=</span><span style="color:#0F4880;"> &#39;Rodriguez&#39;</span></span>
<span class="line"><span style="color:#0A121C;">LIMIT </span><span style="color:#22313F;">100</span></span></code></pre></div></li><li><p>Run the query again.</p><p>You should now see a single record: the consolidated profile created by the identity resolution process.</p></li></ol>`,3)]))}const g=a(l,[["render",i]]);export{h as __pageData,g as default};
