import{_ as a,c as n,a1 as l,o as e}from"./chunks/framework.BRP8cXOc.js";const o="/agentforce-workshop/prompt-builder-flex-data-cloud.rqhZrE6g.webp",h=JSON.parse('{"title":"Exercise 4: Ground a Prompt with Data Cloud","description":"","frontmatter":{},"headers":[],"relativePath":"agentforce-workshop/prompt-builder/4-data-cloud.md","filePath":"agentforce-workshop/prompt-builder/4-data-cloud.md"}'),p={name:"agentforce-workshop/prompt-builder/4-data-cloud.md"};function t(r,s,c,i,y,d){return e(),n("div",null,s[0]||(s[0]=[l(`<h1 id="exercise-4-ground-a-prompt-with-data-cloud" tabindex="-1">Exercise 4: Ground a Prompt with Data Cloud <a class="header-anchor" href="#exercise-4-ground-a-prompt-with-data-cloud" aria-label="Permalink to &quot;Exercise 4: Ground a Prompt with Data Cloud&quot;">​</a></h1><p>In this exercise, you&#39;ll query the Reservation object in Data Cloud to get the check-in date for a guest&#39;s next stay. You&#39;ll then use that check-in date in the <strong>Welcome Email for Upcoming Trip</strong> template you created in Exercise 3.</p><h2 id="step-1-examine-the-apex-class-that-queries-data-cloud-data" tabindex="-1">Step 1: Examine the Apex class that queries Data Cloud data <a class="header-anchor" href="#step-1-examine-the-apex-class-that-queries-data-cloud-data" aria-label="Permalink to &quot;Step 1: Examine the Apex class that queries Data Cloud data&quot;">​</a></h2><ol><li><p>From Setup, Search for <strong>Apex</strong> and click <strong>Apex Classes</strong>.</p></li><li><p>Open the <strong>GetCheckinDate</strong> class.</p><div class="language-apex"><button title="Copy Code" class="copy"></button><span class="lang">apex</span><pre class="shiki Codey High Noon vp-code" tabindex="0"><code><span class="line"><span style="color:#000060;">public</span><span style="color:#550000;"> with sharing</span><span style="color:#2A150D;"> class</span><span style="color:#550000;"> GetCheckinDate</span><span style="color:#005555;"> {</span></span>
<span class="line"><span style="color:#0A121C;">   </span></span>
<span class="line"><span style="color:#1F3A93;">   @InvocableMethod</span></span>
<span class="line"><span style="color:#000060;">   public</span><span style="color:#000060;"> static</span><span style="color:#1F3A93;"> List</span><span style="color:#005555;">&lt;</span><span style="color:#1F3A93;">Response</span><span style="color:#005555;">&gt;</span><span style="color:#914F15;"> getDate</span><span style="color:#005555;">(</span><span style="color:#1F3A93;">List</span><span style="color:#005555;">&lt;</span><span style="color:#1F3A93;">Request</span><span style="color:#005555;">&gt;</span><span style="color:#1460AA;"> requests</span><span style="color:#005555;">)</span><span style="color:#005555;"> {</span></span>
<span class="line"><span style="color:#1F3A93;">      Request</span><span style="color:#0A3055;"> input</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span><span style="color:#0A3055;"> requests</span><span style="color:#005555;">[</span><span style="color:#22313F;">0</span><span style="color:#005555;">];</span></span>
<span class="line"><span style="color:#1F3A93;">      Contact</span><span style="color:#0A3055;"> contact</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span><span style="color:#0A3055;"> input</span><span style="color:#005555;">.</span><span style="color:#0A3055;">Recipient</span><span style="color:#005555;">;</span></span>
<span class="line"><span style="color:#2A150D;">      String</span><span style="color:#0A3055;"> nextCheckInDate</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span><span style="color:#2D74A7;"> null</span><span style="color:#005555;">;</span></span>
<span class="line"><span style="color:#6C7076;">      // Create input for query operation</span></span>
<span class="line"><span style="color:#1F3A93;">      ConnectApi</span><span style="color:#005555;">.</span><span style="color:#1F3A93;">CdpQueryInput</span><span style="color:#0A3055;"> queryInput</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span><span style="color:#2A150D;"> new</span><span style="color:#1F3A93;"> ConnectApi</span><span style="color:#005555;">.</span><span style="color:#1F3A93;">CdpQueryInput</span><span style="color:#005555;">();</span></span>
<span class="line"><span style="color:#0A3055;">      queryInput</span><span style="color:#005555;">.</span><span style="color:#0A3055;">sql</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span></span>
<span class="line"><span style="color:#0F4880;">         &#39;SELECT MIN(Check_in_Date__c) FROM Reservation__dlm JOIN UnifiedLinkssotIndividualCcid__dlm ON Contact_ID__c = SourceRecordId__c WHERE Check_in_Date__c &gt;= NOW() AND UnifiedRecordId__c = (SELECT UnifiedRecordId__c FROM UnifiedLinkssotIndividualCcid__dlm WHERE SourceRecordId__c=\\&#39;&#39;</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;">+</span><span style="color:#0A3055;">contact</span><span style="color:#005555;">.</span><span style="color:#0A3055;">Id</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;">+</span><span style="color:#0F4880;">&#39;\\&#39;)&#39;</span><span style="color:#005555;">;</span></span>
<span class="line"><span style="color:#6C7076;">      // Execute SQL</span></span>
<span class="line"><span style="color:#1F3A93;">      ConnectApi</span><span style="color:#005555;">.</span><span style="color:#1F3A93;">CdpQueryOutputV2</span><span style="color:#0A3055;"> response</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span><span style="color:#0A3055;"> ConnectApi</span><span style="color:#005555;">.</span><span style="color:#0A3055;">CdpQuery</span><span style="color:#005555;">.</span><span style="color:#914F15;">queryAnsiSqlV2</span><span style="color:#005555;">(</span><span style="color:#0A3055;">queryInput</span><span style="color:#005555;">);</span></span>
<span class="line"><span style="color:#2A150D;">      if</span><span style="color:#005555;"> (</span><span style="color:#0A3055;">response</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> !=</span><span style="color:#2D74A7;"> null</span><span style="color:#0A121C;"> &amp;&amp; </span><span style="color:#0A3055;">response</span><span style="color:#005555;">.</span><span style="color:#0A3055;">data</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> !=</span><span style="color:#2D74A7;"> null</span><span style="color:#0A121C;"> &amp;&amp; !</span><span style="color:#0A3055;">response</span><span style="color:#005555;">.</span><span style="color:#0A3055;">data</span><span style="color:#005555;">.</span><span style="color:#914F15;">isEmpty</span><span style="color:#005555;">())</span><span style="color:#005555;"> {</span></span>
<span class="line"><span style="color:#1F3A93;">         ConnectApi</span><span style="color:#005555;">.</span><span style="color:#1F3A93;">CdpQueryV2Row</span><span style="color:#0A3055;"> resultRow</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span><span style="color:#0A3055;"> response</span><span style="color:#005555;">.</span><span style="color:#0A3055;">data</span><span style="color:#005555;">[</span><span style="color:#22313F;">0</span><span style="color:#005555;">];</span></span>
<span class="line"><span style="color:#2A150D;">         Object</span><span style="color:#0A3055;"> rowDataValue</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span><span style="color:#0A3055;"> resultRow</span><span style="color:#005555;">.</span><span style="color:#0A3055;">rowData</span><span style="color:#005555;">[</span><span style="color:#22313F;">0</span><span style="color:#005555;">];</span></span>
<span class="line"><span style="color:#2A150D;">         if</span><span style="color:#005555;"> (</span><span style="color:#0A3055;">rowDataValue</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> !=</span><span style="color:#2D74A7;"> null</span><span style="color:#0A121C;"> &amp;&amp; </span><span style="color:#0A3055;">rowDataValue</span><span style="color:#0A3055;"> instanceof</span><span style="color:#0A3055;"> String</span><span style="color:#005555;">)</span><span style="color:#005555;"> {</span></span>
<span class="line"><span style="color:#0A3055;">            nextCheckInDate</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span><span style="color:#005555;"> (</span><span style="color:#2A150D;">String</span><span style="color:#005555;">)</span><span style="color:#0A3055;"> rowDataValue</span><span style="color:#005555;">;</span></span>
<span class="line"><span style="color:#005555;">         }</span></span>
<span class="line"><span style="color:#005555;">      }</span></span>
<span class="line"><span style="color:#6C7076;">      // Create response</span></span>
<span class="line"><span style="color:#1F3A93;">      List</span><span style="color:#005555;">&lt;</span><span style="color:#1F3A93;">Response</span><span style="color:#005555;">&gt;</span><span style="color:#0A3055;"> responses</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span><span style="color:#2A150D;"> new</span><span style="color:#1F3A93;"> List</span><span style="color:#005555;">&lt;</span><span style="color:#1F3A93;">Response</span><span style="color:#005555;">&gt;();</span></span>
<span class="line"><span style="color:#1F3A93;">      Response</span><span style="color:#0A3055;"> res</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span><span style="color:#2A150D;"> new</span><span style="color:#1F3A93;"> Response</span><span style="color:#005555;">();</span></span>
<span class="line"><span style="color:#0A3055;">      res</span><span style="color:#005555;">.</span><span style="color:#0A3055;">Prompt</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;"> =</span><span style="color:#0A3055;"> nextCheckInDate</span><span style="color:#005555;">;</span></span>
<span class="line"><span style="color:#0A3055;">      responses</span><span style="color:#005555;">.</span><span style="color:#914F15;">add</span><span style="color:#005555;">(</span><span style="color:#0A3055;">res</span><span style="color:#005555;">);</span></span>
<span class="line"><span style="color:#2A150D;">      return</span><span style="color:#0A3055;"> responses</span><span style="color:#005555;">;</span></span>
<span class="line"><span style="color:#005555;">   }</span></span>
<span class="line"></span>
<span class="line"><span style="color:#6C7076;">   // The variables in this class need to match the prompt template inputs,</span></span>
<span class="line"><span style="color:#6C7076;">   // that may be different on each prompt template</span></span>
<span class="line"><span style="color:#000060;">   public</span><span style="color:#2A150D;"> class</span><span style="color:#550000;"> Request</span><span style="color:#005555;"> {</span></span>
<span class="line"><span style="color:#1F3A93;">      @InvocableVariable</span><span style="color:#005555;">(</span><span style="color:#0A3055;">required</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;">=</span><span style="color:#58007E;">true</span><span style="color:#005555;">)</span></span>
<span class="line"><span style="color:#000060;">      public</span><span style="color:#1F3A93;"> Contact</span><span style="color:#0A3055;"> Recipient</span><span style="color:#005555;">;</span></span>
<span class="line"><span style="color:#1F3A93;">      @InvocableVariable</span><span style="color:#005555;">(</span><span style="color:#0A3055;">required</span><span style="color:#2C3E50;font-style:italic;font-weight:bold;">=</span><span style="color:#58007E;">true</span><span style="color:#005555;">)</span></span>
<span class="line"><span style="color:#000060;">      public</span><span style="color:#1F3A93;"> User</span><span style="color:#0A3055;"> Sender</span><span style="color:#005555;">;</span></span>
<span class="line"><span style="color:#005555;">   }</span></span>
<span class="line"><span style="color:#000060;">   public</span><span style="color:#2A150D;"> class</span><span style="color:#550000;"> Response</span><span style="color:#005555;"> {</span></span>
<span class="line"><span style="color:#1F3A93;">      @InvocableVariable</span></span>
<span class="line"><span style="color:#000060;">      public</span><span style="color:#2A150D;"> String</span><span style="color:#0A3055;"> Prompt</span><span style="color:#005555;">;</span></span>
<span class="line"><span style="color:#005555;">   }</span></span>
<span class="line"><span style="color:#005555;">}</span></span></code></pre></div></li><li><p>Notice the <strong>queryAnsiSqlV2</strong> method that&#39;s used to fire a SQL query to get data from Data Cloud.</p></li></ol><h2 id="step-2-ground-the-prompt-template-with-data-cloud-data" tabindex="-1">Step 2: Ground the prompt template with Data Cloud data <a class="header-anchor" href="#step-2-ground-the-prompt-template-with-data-cloud-data" aria-label="Permalink to &quot;Step 2: Ground the prompt template with Data Cloud data&quot;">​</a></h2><ol><li><p>In Setup, open <strong>Prompt Builder</strong>.</p></li><li><p>Open the <strong>Welcome Email for Upcoming Trip</strong> template.</p></li><li><p>Replace the <code>Input:Recipient.Next_Check_in_Date__c</code> merge field with the check-in date retrieved by the Data Cloud query in your Apex class: use the Resource Search box and select <strong>Apex &gt; GetCheckinDate</strong>.</p></li><li><p>Click <strong>Save As &gt; Save as New Version</strong>.</p></li><li><p>In the Preview panel, select <strong>Aarika Jaray</strong> as the Contact.</p></li><li><p>Click <strong>Preview</strong>.</p><p><img src="`+o+'" alt="" data-zoomable="true"></p><ul><li><p>In the <strong>Resolution</strong> panel, examine the prompt that was generated. Notice that the Apex merge field in the template has been replaced with the check-in date for the guest&#39;s next stay obtained by the Invocable Apex method.</p></li><li><p>In the <strong>Response</strong> panel, examine the message generated by the LLM including the actual check-in date.</p></li></ul></li></ol>',6)]))}const A=a(p,[["render",t]]);export{h as __pageData,A as default};
